version: '3.5'

services:
  smooth-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: smooth-app
    ports:
      - 80:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    networks:
      backend:
        aliases:
          - app
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    command: --sql_mode=""
    ports:
        - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - mysql-db
  mysql-db-test:
    image: mysql:5.7
    container_name: mysql-db-test
    volumes:
      - ./run/var-test:/var/lib/mysql
    command: --sql_mode=""
    ports:
        - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - mysql-db
networks:
  backend:
    name: backend-network
